using System.Data;
using System.Drawing;
using CloudyWing.SpreadsheetExporter.Templates;
using CloudyWing.SpreadsheetExporter.Templates.DataTable;

namespace CloudyWing.SpreadsheetExporter.Tests.Templates.DataTable {
    [TestFixture]
    internal class DataTableTemplateTests {
        private System.Data.DataTable dataTable;
        private DataTableTemplate template;

        [SetUp]
        public void SetUp() {
            dataTable = new System.Data.DataTable();
            dataTable.Columns.Add("Id", typeof(int));
            dataTable.Columns.Add("Name", typeof(string));
            dataTable.Columns.Add("Age", typeof(int));

            dataTable.Rows.Add(1, "Alice", 30);
            dataTable.Rows.Add(2, "Bob", 25);
            dataTable.Rows.Add(3, "Charlie", 35);

            template = new DataTableTemplate(dataTable);
        }

        [Test]
        public void Constructor_NullDataTable_ThrowsArgumentNullException() {
            Assert.Throws<ArgumentNullException>(() => new DataTableTemplate(null));
        }

        [Test]
        public void ColumnSpan_WithAutoGeneratedColumns_ReturnsCorrectValue() {
            Assert.That(template.ColumnSpan, Is.EqualTo(3));
        }

        [Test]
        public void RowSpan_WithDataRows_ReturnsCorrectValue() {
            // RowSpan = DataTable.Rows.Count + 1 (header row)
            Assert.That(template.RowSpan, Is.EqualTo(4));
        }

        [Test]
        public void Constructor_AutoGeneratesColumns() {
            Assert.That(template.Columns, Has.Count.EqualTo(3));
            Assert.That(template.Columns[0].ColumnName, Is.EqualTo("Id"));
            Assert.That(template.Columns[0].HeaderText, Is.EqualTo("Id"));
            Assert.That(template.Columns[1].ColumnName, Is.EqualTo("Name"));
            Assert.That(template.Columns[1].HeaderText, Is.EqualTo("Name"));
            Assert.That(template.Columns[2].ColumnName, Is.EqualTo("Age"));
            Assert.That(template.Columns[2].HeaderText, Is.EqualTo("Age"));
        }

        [Test]
        public void GetContext_NoColumns_ReturnsEmptyCells() {
            template.Columns.Clear();
            TemplateContext context = template.GetContext();

            Assert.That(context.Cells, Is.Empty);
        }

        [Test]
        public void GetContext_WithAutoGeneratedColumns_ReturnsCorrectCells() {
            TemplateContext context = template.GetContext();

            // Total cells = (header row + data rows) * columns = (1 + 3) * 3 = 12
            Assert.That(context.Cells, Has.Count.EqualTo(12));
        }

        [Test]
        public void GetContext_HeaderCells_HaveCorrectPositions() {
            TemplateContext context = template.GetContext();
            var headerCells = context.Cells.Where(c => c.Point.Y == 0).OrderBy(c => c.Point.X).ToList();

            Assert.That(headerCells, Has.Count.EqualTo(3));
            Assert.That(headerCells[0].Point, Is.EqualTo(new Point(0, 0)));
            Assert.That(headerCells[1].Point, Is.EqualTo(new Point(1, 0)));
            Assert.That(headerCells[2].Point, Is.EqualTo(new Point(2, 0)));
        }

        [Test]
        public void GetContext_HeaderCells_HaveCorrectValues() {
            TemplateContext context = template.GetContext();
            var headerCells = context.Cells.Where(c => c.Point.Y == 0).OrderBy(c => c.Point.X).ToList();

            Assert.That(headerCells[0].ValueGenerator(0, 0), Is.EqualTo("Id"));
            Assert.That(headerCells[1].ValueGenerator(0, 0), Is.EqualTo("Name"));
            Assert.That(headerCells[2].ValueGenerator(0, 0), Is.EqualTo("Age"));
        }

        [Test]
        public void GetContext_DataCells_HaveCorrectValues() {
            TemplateContext context = template.GetContext();
            var dataCells = context.Cells.Where(c => c.Point.Y > 0).OrderBy(c => c.Point.Y).ThenBy(c => c.Point.X).ToList();

            // First row (Alice)
            Assert.That(dataCells[0].ValueGenerator(0, 1), Is.EqualTo(1));
            Assert.That(dataCells[1].ValueGenerator(1, 1), Is.EqualTo("Alice"));
            Assert.That(dataCells[2].ValueGenerator(2, 1), Is.EqualTo(30));

            // Second row (Bob)
            Assert.That(dataCells[3].ValueGenerator(0, 2), Is.EqualTo(2));
            Assert.That(dataCells[4].ValueGenerator(1, 2), Is.EqualTo("Bob"));
            Assert.That(dataCells[5].ValueGenerator(2, 2), Is.EqualTo(25));

            // Third row (Charlie)
            Assert.That(dataCells[6].ValueGenerator(0, 3), Is.EqualTo(3));
            Assert.That(dataCells[7].ValueGenerator(1, 3), Is.EqualTo("Charlie"));
            Assert.That(dataCells[8].ValueGenerator(2, 3), Is.EqualTo(35));
        }

        [Test]
        public void GetContext_WithDBNull_ConvertsToNull() {
            dataTable.Rows.Add(4, DBNull.Value, DBNull.Value);
            template = new DataTableTemplate(dataTable);

            TemplateContext context = template.GetContext();
            var lastRowCells = context.Cells.Where(c => c.Point.Y == 4).OrderBy(c => c.Point.X).ToList();

            Assert.That(lastRowCells[0].ValueGenerator(0, 4), Is.EqualTo(4));
            Assert.That(lastRowCells[1].ValueGenerator(1, 4), Is.Null);
            Assert.That(lastRowCells[2].ValueGenerator(2, 4), Is.Null);
        }

        [Test]
        public void GetContext_WithCustomHeaderText_UsesCustomText() {
            template.Columns.Clear();
            template.Columns.Add(new DataTableColumn {
                ColumnName = "Id",
                HeaderText = "編號"
            });
            template.Columns.Add(new DataTableColumn {
                ColumnName = "Name",
                HeaderText = "姓名"
            });

            TemplateContext context = template.GetContext();
            var headerCells = context.Cells.Where(c => c.Point.Y == 0).OrderBy(c => c.Point.X).ToList();

            Assert.That(headerCells[0].ValueGenerator(0, 0), Is.EqualTo("編號"));
            Assert.That(headerCells[1].ValueGenerator(0, 0), Is.EqualTo("姓名"));
        }

        [Test]
        public void GetContext_WithFieldValueGenerator_AppliesTransformation() {
            template.Columns.Clear();
            template.Columns.Add(new DataTableColumn {
                ColumnName = "Name",
                HeaderText = "Name",
                FieldValueGenerator = value => value?.ToString()?.ToUpper()
            });

            TemplateContext context = template.GetContext();
            var dataCells = context.Cells.Where(c => c.Point.Y > 0 && c.Point.X == 0).OrderBy(c => c.Point.Y).ToList();

            Assert.That(dataCells[0].ValueGenerator(0, 1), Is.EqualTo("ALICE"));
            Assert.That(dataCells[1].ValueGenerator(0, 2), Is.EqualTo("BOB"));
            Assert.That(dataCells[2].ValueGenerator(0, 3), Is.EqualTo("CHARLIE"));
        }

        [Test]
        public void GetContext_WithHeaderHeight_SetsCorrectRowHeight() {
            template.HeaderHeight = 20;

            TemplateContext context = template.GetContext();

            Assert.That(context.RowHeights[0], Is.EqualTo(20));
        }

        [Test]
        public void GetContext_WithRecordHeight_SetsCorrectRowHeights() {
            template.RecordHeight = 15;

            TemplateContext context = template.GetContext();

            Assert.That(context.RowHeights[1], Is.EqualTo(15));
            Assert.That(context.RowHeights[2], Is.EqualTo(15));
            Assert.That(context.RowHeights[3], Is.EqualTo(15));
        }

        [Test]
        public void GetContext_WithCustomHeaderStyle_AppliesStyle() {
            CellStyle customStyle = new() { Font = new CellFont(Style: FontStyles.IsBold) };
            template.Columns.Clear();
            template.Columns.Add(new DataTableColumn {
                ColumnName = "Name",
                HeaderText = "Name",
                HeaderStyle = customStyle
            });

            TemplateContext context = template.GetContext();
            var headerCell = context.Cells.First(c => c.Point.Y == 0);

            Assert.That(headerCell.CellStyleGenerator(0, 0), Is.EqualTo(customStyle));
        }

        [Test]
        public void GetContext_WithCustomFieldStyleGenerator_AppliesStyle() {
            CellStyle customStyle = new() { Font = new CellFont(Style: FontStyles.IsBold) };
            template.Columns.Clear();
            template.Columns.Add(new DataTableColumn {
                ColumnName = "Age",
                HeaderText = "Age",
                FieldStyleGenerator = value => (int)value > 30 ? customStyle : SpreadsheetManager.DefaultCellStyles.FieldStyle
            });

            TemplateContext context = template.GetContext();
            var dataCells = context.Cells.Where(c => c.Point.Y > 0 && c.Point.X == 0).OrderBy(c => c.Point.Y).ToList();

            Assert.That(dataCells[0].CellStyleGenerator(0, 1), Is.EqualTo(SpreadsheetManager.DefaultCellStyles.FieldStyle)); // Alice, 30
            Assert.That(dataCells[1].CellStyleGenerator(0, 2), Is.EqualTo(SpreadsheetManager.DefaultCellStyles.FieldStyle)); // Bob, 25
            Assert.That(dataCells[2].CellStyleGenerator(0, 3), Is.EqualTo(customStyle)); // Charlie, 35
        }

        [Test]
        public void GetContext_WithFieldFormulaGenerator_AppliesFormula() {
            template.Columns.Clear();
            template.Columns.Add(new DataTableColumn {
                ColumnName = "Age",
                HeaderText = "Age",
                FieldFormulaGenerator = value => $"A{value}"
            });

            TemplateContext context = template.GetContext();
            var dataCell = context.Cells.First(c => c.Point.Y == 1 && c.Point.X == 0);

            Assert.That(dataCell.FormulaGenerator(0, 1), Is.EqualTo("A30"));
        }
    }
}
